spring:
  datasource:
    # default to H2 in-memory for initial dev; swap to postgres later
    url: jdbc:h2:mem:salesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false   # enable when we add migrations

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

# jwt.secret and other secrets will be added later via env vars
