spring:
  datasource:
    url: jdbc:h2:file:./data/salesdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations: classpath:db.migration

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.example.sales.security: DEBUG
    io.jsonwebtoken: DEBUG

jwt:
  secret: ${JWT_SECRET:change-me-super-secret-please-change}
  expirationMs: ${JWT_EXP_MS:3600000}
